name: Claude Code PR Bot

on:
  issue_comment:
    types: [created]

jobs:
  test-bot:
    if: contains(github.event.comment.body, '/claude')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Claude bot triggered!"