name: email-min auto (SAFE dummy)

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: read
  pull-requests: write

env:
  EMAIL_FROM: ${{ secrets.EMAIL_FROM || 'no-reply@example.com' }}
  EMAIL_TO_DEFAULT: ${{ secrets.EMAIL_TO_DEFAULT || 'recipient@example.com' }}
  EMAIL_DRY_RUN: 'true'

jobs:
  auto-preview:
    # 条件: ラベル 'run-email-dummy' が付いているPRのみ実行
    if: contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'run-email-dummy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate dummy email (.eml)
        run: |
          bash scripts/email_dummy_send.sh \
            --from "${EMAIL_FROM}" \
            --to  "${EMAIL_TO_DEFAULT}" \
            --subject "Auto SAFE dummy for PR #${{ github.event.number }}" \
            --body "This is an automated SAFE dummy run."
      - name: Upload outbox artifact
        uses: actions/upload-artifact@v4
        with:
          name: outbox
          path: reports/outbox/*.eml
      - name: Comment artifact link to PR
        uses: actions/github-script@v7
        with:
          script: |
            const runUrl = `${{ toJson(github.server_url) }}/${{ toJson(github.repository) }}/actions/runs/${{ toJson(github.run_id) }}`
            const body = [
              "✅ SAFE dummy mail run completed.",
              "",
              `- Download **outbox** artifact here: ${runUrl}`,
              "- This run generated `.eml` files (no real sending)."
            ].join("\n")
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            })